stages:
  download_data:
    cmd: python scripts/download.py
    outs:
      - data/iris_dataset.csv
  process_data:
    cmd: python scripts/process_data.py
    deps:
      - data/iris_dataset.csv
      - scripts/process_data.py
    outs:
      - data/proc_iris_dataset.csv
